### DISCUSSION TITLE
Where can I add access log format?

### DISCUSSION THREAD

**Discussion by rmalenko** [nginx/ansible-role-nginx-config#365] [Q&A] [answered]
Where can I add the access log format?

Prompt me, please.
There is part of my playbook where I have added log_format. But this doesn't create correct nginx. conf.

```yaml
    - name: Configure NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx_config
      vars:
        nginx_config_debug_output: true
        ...
          template_file: nginx.conf.j2
          deployment_location: /etc/nginx/nginx.conf
        ...
            http:
              log:
                format:
                  - name: main
                    format: |
                      '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"'
              include:
                - /etc/nginx/conf.d/*.conf
                - /etc/nginx/conf.d/backend/*.conf
```
