### DISCUSSION TITLE
How to use include in locations block

### DISCUSSION THREAD

**Discussion by tibz7** [nginx/ansible-role-nginx-config#386] [General]
I'm trying to make a generic location that i want to be able to include in multiple domains, something like:

``` 
location /endpoint {
    internal true;
}
```
And I want to include that in each `server` block where i need it. 

The problem is that the role forces you to use the "hierarchy" so i end up writting:
```
- deployment_location: /etc/nginx/includes/common_locations.conf
  config:
    servers:
      - core:
        locations:
          - location: ^~ /endpoint
            internal: true

```

which renders as 
```
server {
location /endpoint {
   internal true; 
}
location /endpoint2 {
...
}
}

````

but that cannot be included in the server bloc. If I include it one level above, it does not work...

**Comment by alessfg** [comment]
The `internal` directive is only allowed within `location` blocks. Check https://nginx.org/en/docs/http/ngx_http_core_module.html#internal for more details 🙂

**Reply by tibz7** [reply]
yes this is exactly my problem :smile: 

I cannot make an include of a file containing only locations inside a server block . according to the documentation this is actually possible, but the role does not let me do that. 
the best I could do is an include of a server block containing my location within a host configuration. but then it does not work

**Comment by oxpa** [comment]
@tibz7 could you please add some details: why do you need it in an include? To be more specific, I don't quite get why would you need an include for a configuration managed by ansible.
If you have a repeating snippet you may reuse yaml nodes within a file. Would this suffice?

**Reply by tibz7** [reply]
yeah the yaml nodes are a good alternative, I did not think of them!\
but I need this repeating snipped over multiple config files. I want to make a specific endpoint internal and that endpoint is on multiple server configuration

**Reply by oxpa** [reply]
I think I get what you want.
For now, I can suggest using custom_directives in `default.conf.j2` template and include that.
The long term solution is to rework templates slightly to have `location` blocks and internals separated from `server` blocks.

**Reply by tibz7** [reply]
ok so i should create a custom_directive that contains a location block and include it in the server blocks where that is needed, right?

**Reply by oxpa** [reply]
I looked through templates and I'm not sure if it is even possible to include anything into a server block.
So you will have to use custom directives to include the file into a server or a location block.

And it's not trivial to make include work everywhere, sadly.

**Reply by tibz7** [reply]
yes thats what I was affrayed of... It seems that using it with ansible is not very useful.

**Reply by oxpa** [reply]
¯\\_(ツ)_/¯

**Reply by alessfg** [reply]
You should be able to include files/snippets/conf files in both the server and location block by doing something like:
```yaml
servers:
  - core:
      include: /path/to/server/snippet
    locations:
      - location: /
        core:
          include: /path/to/location/snippet
```

In so far as creating snippets/conf files that directly create a location block (sans the wrapping server block) -- that's definitely not possible at this time. It's definitely worth investigating how feasible it'd be to implement!

**Reply by tibz7** [reply]
yeah i wrote someting like that initially

```
server:
 server_name: blabla
  include: /path/to/snippet
```
and snippet
```
servers:
server:
   locations:
       location:  /myendpoint
       core:
         .....
```
